import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ur" | "ps" | "bal" | "brh" | "fa" | "pa" | "sd";

// ── Translations ─────────────────────────────────────────────────────────────
const T = {
  en: {
    hotelName:      "Quetta Hotel",
    welcome:        "Welcome",
    enterName:      "Enter your name to continue",
    namePlaceholder:"Your name or table number",
    continueBtn:    "Continue",
    changeName:     "Change",
    menu:           "Menu",
    myOrders:       "My Orders",
    addToCart:      "Add",
    placeOrder:     "Place Order",
    orderSummary:   "Order Summary",
    total:          "Total",
    confirmOrder:   "Confirm Order",
    cancel:         "Cancel",
    orderPlaced:    "Order placed",
    status: {
      pending:   "Pending",
      preparing: "Cooking",
      ready:     "Ready",
      served:    "Served",
      paid:      "Paid",
      cancelled: "Cancelled",
    },
    payStatus: { unpaid: "Unpaid", partial: "Partial", paid: "Paid" },
    // dashboard
    adminPanel:     "Admin Panel",
    todayRevenue:   "Today's Revenue",
    inKitchen:      "In Kitchen",
    ready2:         "Ready",
    unpaidOrders:   "Unpaid",
    orders:         "Orders",
    inventory:      "Supplies",
    stock:          "Utensils",
    searchOrders:   "Search by name or order #...",
    all:            "All",
    unpaidFilter:   "Unpaid",
    queueFilter:    "Queue",
    readyFilter:    "Ready",
    paidFilter:     "Paid",
    takePayment:    "Take Payment",
    cancelOrder:    "Cancel",
    newOrder:       "New Order",
    cashSplit:      "Cash",
    bankSplit:      "Bank",
    // payment sheet
    payment:        "Payment",
    billFor:        "Bill for",
    grandTotal:     "Grand Total",
    alreadyPaid:    "Already Paid",
    remaining:      "Remaining",
    howMuch:        "How much paid? (Rs.)",
    fillFull:       "Fill full amount",
    payMethod:      "Payment Method",
    cash:           "Cash",
    bank:           "Bank Transfer",
    save:           "Save",
    back:           "Back",
    // waiter
    waiterView:     "Waiter View",
    readyToServe:   "Ready to Serve",
    recentlyServed: "Recently Served",
    markServed:     "Mark Served",
    noOrdersReady:  "No orders ready",
    // kitchen
    kitchenDisplay: "Kitchen Display",
    startCooking:   "Start Cooking",
    readyToServeBtn:"Ready to Serve",
    noOrders:       "No pending orders",
    // autofill
    tapToAutofill:  "Tap to autofill: ",
    // confirmation dialogs
    confirmCancel:     "Cancel this order?",
    confirmCancelDesc: "This action cannot be undone.",
    confirm:           "Confirm",
  },
  ur: {
    hotelName:      "کوئٹہ ہوٹل",
    welcome:        "خوش آمدید",
    enterName:      "جاری رکھنے کے لیے اپنا نام لکھیں",
    namePlaceholder:"آپ کا نام یا ٹیبل نمبر",
    continueBtn:    "آگے بڑھیں",
    changeName:     "نام بدلیں",
    menu:           "مینو",
    myOrders:       "میرے آرڈر",
    addToCart:      "شامل کریں",
    placeOrder:     "آرڈر کریں",
    orderSummary:   "آرڈر کی تفصیل",
    total:          "کل",
    confirmOrder:   "آرڈر کنفرم کریں",
    cancel:         "منسوخ",
    orderPlaced:    "آرڈر مل گیا",
    status: {
      pending:   "انتظار",
      preparing: "بن رہا ہے",
      ready:     "تیار",
      served:    "دے دیا",
      paid:      "ادا",
      cancelled: "منسوخ",
    },
    payStatus: { unpaid: "باقی", partial: "ادھا", paid: "ادا" },
    adminPanel:     "ایڈمن",
    todayRevenue:   "آج کی گلہ",
    inKitchen:      "باورچی خانے میں",
    ready2:         "تیار",
    unpaidOrders:   "باقی",
    orders:         "آرڈر",
    inventory:      "سامان",
    stock:          "برتن",
    searchOrders:   "نام یا نمبر سے تلاش کریں",
    all:            "سب",
    unpaidFilter:   "باقی",
    queueFilter:    "قطار",
    readyFilter:    "تیار",
    paidFilter:     "ادا",
    takePayment:    "پیسے لیں",
    cancelOrder:    "منسوخ",
    newOrder:       "نیا آرڈر",
    cashSplit:      "نقد",
    bankSplit:      "بینک",
    payment:        "ادائیگی",
    billFor:        "بل",
    grandTotal:     "کل رقم",
    alreadyPaid:    "پہلے دیا",
    remaining:      "باقی",
    howMuch:        "کتنے پیسے؟ (روپے)",
    fillFull:       "پوری رقم بھریں",
    payMethod:      "ادائیگی کا طریقہ",
    cash:           "نقد",
    bank:           "بینک ٹرانسفر",
    save:           "محفوظ کریں",
    back:           "واپس",
    waiterView:     "ویٹر",
    readyToServe:   "دینے کے لیے تیار",
    recentlyServed: "حال ہی میں دیا",
    markServed:     "دے دیا",
    noOrdersReady:  "کوئی آرڈر تیار نہیں",
    kitchenDisplay: "باورچی خانہ",
    startCooking:   "پکانا شروع کریں",
    readyToServeBtn:"تیار ہے",
    noOrders:       "کوئی آرڈر نہیں",
    tapToAutofill:  "آٹو فل کرنے کے لیے کلک کریں: ",
    confirmCancel:     "یہ آرڈر منسوخ کریں؟",
    confirmCancelDesc: "یہ عمل واپس نہیں ہو سکتا۔",
    confirm:           "تصدیق کریں",
  },
  ps: {
    hotelName:      "کوټه هوټل",
    welcome:        "ښه راغلاست",
    enterName:      "د دوام لپاره خپل نوم ولیکئ",
    namePlaceholder:"ستاسو نوم یا میز نمبر",
    continueBtn:    "مخ پر ځه",
    changeName:     "نوم بدل کړئ",
    menu:           "مینو",
    myOrders:       "زما آرډرونه",
    addToCart:      "اضافه کړئ",
    placeOrder:     "آرډر کړئ",
    orderSummary:   "د آرډر لنډیز",
    total:          "ټول",
    confirmOrder:   "آرډر تایید کړئ",
    cancel:         "لغوه کړئ",
    orderPlaced:    "آرډر ومنل شو",
    status: {
      pending:   "انتظار",
      preparing: "پخیږي",
      ready:     "چمتو",
      served:    "ورکړل شو",
      paid:      "ورکړل شو",
      cancelled: "لغوه",
    },
    payStatus: { unpaid: "پاتې", partial: "نیمه", paid: "ورکړل شو" },
    adminPanel:     "ادمین",
    todayRevenue:   "د نن ورځې عاید",
    inKitchen:      "پخلي کې",
    ready2:         "چمتو",
    unpaidOrders:   "پاتې",
    orders:         "آرډرونه",
    inventory:      "سامان",
    stock:          "لوښي",
    searchOrders:   "نوم یا نمبر وپلټئ",
    all:            "ټول",
    unpaidFilter:   "پاتې",
    queueFilter:    "لیست",
    readyFilter:    "چمتو",
    paidFilter:     "ورکړل",
    takePayment:    "پیسې واخلئ",
    cancelOrder:    "لغوه",
    newOrder:       "نوی آرډر",
    cashSplit:      "نقده",
    bankSplit:      "بانک",
    payment:        "پیسه",
    billFor:        "بل",
    grandTotal:     "ټول",
    alreadyPaid:    "مخکې ورکړل",
    remaining:      "پاتې",
    howMuch:        "څومره پیسې؟ (Rs.)",
    fillFull:       "بشپړه مبلغ ډک کړئ",
    payMethod:      "د پیسو طریقه",
    cash:           "نقده",
    bank:           "بانک لیږد",
    save:           "خوندي کړئ",
    back:           "بیرته",
    waiterView:     "ویټر",
    readyToServe:   "د وړاندې کولو لپاره چمتو",
    recentlyServed: "پدې وروستیو کې وړاندې شوي",
    markServed:     "وړاندې شو",
    noOrdersReady:  "هیڅ آرډر چمتو نه دی",
    kitchenDisplay: "پخلي",
    startCooking:   "پخول پیل کړئ",
    readyToServeBtn:"چمتو دی",
    noOrders:       "هیڅ آرډر نشته",
    tapToAutofill:  "د آٹو فل لپاره کلک کړئ: ",
    confirmCancel:     "دا آرډر لغوه کړئ؟",
    confirmCancelDesc: "دا کار بیرته نه شي کیدای.",
    confirm:           "تایید کړئ",
  },
  bal: {
    hotelName:      "کوئٹہ ہوٹل",
    welcome:        "وش آتکے",
    enterName:      "دیم ءَ روان بوھگ ءِ ھاتر ءَ وتی نام ءَ بنویس ات",
    namePlaceholder:"وتی نام یا میز ءِ نمبر بنویس ات",
    continueBtn:    "دیم ءَ روان بوھگ",
    changeName:     "نام بدل کنگ",
    menu:           "مینو",
    myOrders:       "منی آرڈر",
    addToCart:      "اوار کنگ",
    placeOrder:     "آرڈر دیگ",
    orderSummary:   "آرڈر ءِ تفصیل",
    total:          "کل",
    confirmOrder:   "آرڈر کنفرم کنگ",
    cancel:         "کینسل",
    orderPlaced:    "آرڈر رس ات",
    status: {
      pending:   "انتظار",
      preparing: "تیار بوھگ ءَ انت",
      ready:     "تیار انت",
      served:    "دیگ بوت",
      paid:      "ادا بوت",
      cancelled: "کینسل بوت",
    },
    payStatus: { unpaid: "باقی", partial: "نیمہ", paid: "ادا" },
    adminPanel:     "ایڈمن",
    todayRevenue:   "مرچیگیں آمدنی",
    inKitchen:      "کچن ءَ",
    ready2:         "تیار انت",
    unpaidOrders:   "باقی",
    orders:         "آرڈر",
    inventory:      "سامان",
    stock:          "برتن",
    searchOrders:   "نام یا نمبر ءَ شوھاز کن",
    all:            "درست",
    unpaidFilter:   "باقی",
    queueFilter:    "قطار",
    readyFilter:    "تیار",
    paidFilter:     "ادا",
    takePayment:    "پیسہ زورگ",
    cancelOrder:    "کینسل",
    newOrder:       "نوکیں آرڈر",
    cashSplit:      "نقد",
    bankSplit:      "بینک",
    payment:        "ادائیگی",
    billFor:        "بل",
    grandTotal:     "کل رقم",
    alreadyPaid:    "پیش ءَ داتگیں",
    remaining:      "باقی",
    howMuch:        "چنت پیسہ؟ (روپیہ)",
    fillFull:       "کلیں رقم ءَ بنویس",
    payMethod:      "ادائیگی ءِ طریقہ",
    cash:           "نقد",
    bank:           "بینک ٹرانسفر",
    save:           "محفوظ کنگ",
    back:           "پشت ءَ",
    waiterView:     "ویٹر",
    readyToServe:   "دیگ ءِ ھاتر ءَ تیار",
    recentlyServed: "سدے داتگیں",
    markServed:     "دیگ بوت",
    noOrdersReady:  "ھیچ آرڈر تیار نہ انت",
    kitchenDisplay: "کچن",
    startCooking:   "پکگ ءَ شروع کن",
    readyToServeBtn:"تیار انت",
    noOrders:       "ھیچ آرڈر نیست",
    tapToAutofill:  "نام آٹو فل کنگ ءِ ھاتر ءَ ادا کلک کن: ",
    confirmCancel:     "ایں آرڈر کینسل کنگ؟",
    confirmCancelDesc: "ایں کار واپس نہ بیت.",
    confirm:           "تصدیق",
  },
  brh: {
    hotelName:      "کوئٹہ ہوٹل",
    welcome:        "بشخ اٹ بسرے",
    enterName:      "مونا ہننگ کن وتی پن ءِ نبشتہ کر",
    namePlaceholder:"وتی پن یا میز ءِ نمبر نبشتہ کر",
    continueBtn:    "مونا ہننگ",
    changeName:     "پن ءِ بدل کر",
    menu:           "مینو",
    myOrders:       "کنا آرڈر آک",
    addToCart:      "اوار کر",
    placeOrder:     "آرڈر ایت",
    orderSummary:   "آرڈر ءِ تفصیل",
    total:          "کل",
    confirmOrder:   "آرڈر ءِ پکائی",
    cancel:         "منسوخ",
    orderPlaced:    "آرڈر ملّا",
    status: {
      pending:   "انتظار",
      preparing: "پکنگ آٹی ءِ",
      ready:     "تیار",
      served:    "تسر",
      paid:      "ادا",
      cancelled: "منسوخ",
    },
    payStatus: { unpaid: "باقی", partial: "نیمہ", paid: "ادا" },
    adminPanel:     "ایڈمن",
    todayRevenue:   "دانو گلہ",
    inKitchen:      "کچن اٹ",
    ready2:         "تیار",
    unpaidOrders:   "باقی",
    orders:         "آرڈر آک",
    inventory:      "سامان",
    stock:          "لوخ آک",
    searchOrders:   "پن یا نمبر اٹ پٹ و پول کر",
    all:            "مچٹ",
    unpaidFilter:   "باقی",
    queueFilter:    "قطار",
    readyFilter:    "تیار",
    paidFilter:     "ادا",
    takePayment:    "پیسہ ہل",
    cancelOrder:    "منسوخ",
    newOrder:       "پوسکن آرڈر",
    cashSplit:      "نقدی",
    bankSplit:      "بینک",
    payment:        "ادائیگی",
    billFor:        "بل",
    grandTotal:     "کل رقم",
    alreadyPaid:    "مست تسونگ",
    remaining:      "باقی",
    howMuch:        "اخس پیسہ؟ (کلدار)",
    fillFull:       "مچ رقم ءِ بھر کر",
    payMethod:      "ادائیگی نا وڑ",
    cash:           "نقدی",
    bank:           "بینک ٹرانسفر",
    save:           "محفوظ کر",
    back:           "پدا",
    waiterView:     "ویٹر",
    readyToServe:   "تننگ کن تیار",
    recentlyServed: "مست تسونگ آک",
    markServed:     "تسر",
    noOrdersReady:  "ہیچ آرڈر تیار اف",
    kitchenDisplay: "کچن",
    startCooking:   "پکنگ ءِ بناء کر",
    readyToServeBtn:"تیار ءِ",
    noOrders:       "ہیچ آرڈر اف",
    tapToAutofill:  "پن ءِ آٹو فل کننگ کن داڑے کلک کر: ",
    confirmCancel:     "ایسا آرڈر منسوخ کر؟",
    confirmCancelDesc: "ایہ ڈول پدا نہ بیت.",
    confirm:           "پکائی",
  },
  fa: {
    hotelName:      "کوئته هتل",
    welcome:        "خوش آمدید",
    enterName:      "برای ادامه نام خود را وارد کنید",
    namePlaceholder:"نام شما یا شماره میز",
    continueBtn:    "ادامه",
    changeName:     "تغییر نام",
    menu:           "منو",
    myOrders:       "سفارشات من",
    addToCart:      "افزودن",
    placeOrder:     "ثبت سفارش",
    orderSummary:   "خلاصه سفارش",
    total:          "مجموع",
    confirmOrder:   "تایید سفارش",
    cancel:         "لغو",
    orderPlaced:    "سفارش ثبت شد",
    status: {
      pending:   "در انتظار",
      preparing: "در حال پخت",
      ready:     "آماده",
      served:    "تحویل داده شده",
      paid:      "پرداخت شده",
      cancelled: "لغو شده",
    },
    payStatus: { unpaid: "پرداخت نشده", partial: "بخشی پرداخت شده", paid: "پرداخت شده" },
    adminPanel:     "پنل مدیریت",
    todayRevenue:   "درآمد امروز",
    inKitchen:      "در آشپزخانه",
    ready2:         "آماده",
    unpaidOrders:   "پرداخت نشده",
    orders:         "سفارشات",
    inventory:      "موجودی کالا",
    stock:          "ظروف و ابزار",
    searchOrders:   "جستجو با نام یا شماره...",
    all:            "همه",
    unpaidFilter:   "پرداخت نشده",
    queueFilter:    "در صف",
    readyFilter:    "آماده",
    paidFilter:     "پرداخت شده",
    takePayment:    "دریافت پرداخت",
    cancelOrder:    "لغو سفارش",
    newOrder:       "سفارش جدید",
    cashSplit:      "نقدی",
    bankSplit:      "بانکی",
    payment:        "پرداخت",
    billFor:        "صورتحساب برای",
    grandTotal:     "کل هزینه",
    alreadyPaid:    "پرداخت شده قبلی",
    remaining:      "باقیمانده",
    howMuch:        "مقدار پرداختی؟ (روپیه)",
    fillFull:       "پر کردن کل مبلغ",
    payMethod:      "روش پرداخت",
    cash:           "نقدی",
    bank:           "انتقال بانکی",
    save:           "ذخیره",
    back:           "بازگشت",
    waiterView:     "نمای ویتر",
    readyToServe:   "آماده برای سرو",
    recentlyServed: "اخیرا سرو شده",
    markServed:     "علامت‌گذاری به عنوان سرو شده",
    noOrdersReady:  "هیچ سفارشی آماده نیست",
    kitchenDisplay: "نمایشگر آشپزخانه",
    startCooking:   "شروع پخت و پز",
    readyToServeBtn:"آماده برای سرو",
    noOrders:       "هیچ سفارش معلقی نیست",
    tapToAutofill:  "برای پر کردن خودکار نام قبلی اینجا کلیک کنید: ",
    confirmCancel:     "این سفارش را لغو کنید؟",
    confirmCancelDesc: "این عمل قابل بازگشت نیست.",
    confirm:           "تایید",
  },
  pa: {
    hotelName:      "کوئٹہ ہوٹل",
    welcome:        "جی آیاں نوں",
    enterName:      "اگے ودھن لئی اپنا ناں لکھو",
    namePlaceholder: "تہاڈا ناں یا ٹیبل نمبر",
    continueBtn:    "اگے ودھو",
    changeName:     "ناں بدلو",
    menu:           "مینو",
    myOrders:       "میرے آرڈر",
    addToCart:      "شامل کرو",
    placeOrder:     "آرڈر دیو",
    orderSummary:   "آرڈر دی تفصیل",
    total:          "کل",
    confirmOrder:   "آرڈر پکا کرو",
    cancel:         "کینسل",
    orderPlaced:    "آرڈر مل گیا",
    status: {
      pending:   "انتظار",
      preparing: "بن رہا اے",
      ready:     "تیار",
      served:    "دے دتا",
      paid:      "ادا",
      cancelled: "منسوخ",
    },
    payStatus: { unpaid: "باقی", partial: "ادھا", paid: "ادا" },
    adminPanel:     "ایڈمن",
    todayRevenue:   "اج دا گلہ",
    inKitchen:      "کچن وچ",
    ready2:         "تیار",
    unpaidOrders:   "باقی",
    orders:         "آرڈرز",
    inventory:      "سامان",
    stock:          "برتن",
    searchOrders:   "ناں یا نمبر نال لبھو",
    all:            "سبھ",
    unpaidFilter:   "باقی",
    queueFilter:    "قطار",
    readyFilter:    "تیار",
    paidFilter:     "ادا",
    takePayment:    "پیسے لوو",
    cancelOrder:    "منسوخ",
    newOrder:       "نواں آرڈر",
    cashSplit:      "نقد",
    bankSplit:      "بینک",
    payment:        "ادائیگی",
    billFor:        "بل",
    grandTotal:     "کل رقم",
    alreadyPaid:    "پہلاں دتا",
    remaining:      "باقی",
    howMuch:        "کنے پیسے؟ (روپے)",
    fillFull:       "پوری رقم بھرو",
    payMethod:      "ادائیگی دا طریقہ",
    cash:           "نقد",
    bank:           "بینک ٹرانسفر",
    save:           "محفوظ کرو",
    back:           "واپس",
    waiterView:     "ویٹر",
    readyToServe:   "دین لئی تیار",
    recentlyServed: "ہونے دتا",
    markServed:     "دے دتا",
    noOrdersReady:  "کوئی آرڈر تیار نہیں",
    kitchenDisplay: "باورچی خانہ",
    startCooking:   "پکانا شروع کرو",
    readyToServeBtn:"تیار اے",
    noOrders:       "کوئی آرڈر نہیں",
    tapToAutofill:  "ناں آٹو فل کرن لئی ایتھے کلک کرو: ",
    confirmCancel:     "ایہ آرڈر کینسل کرو؟",
    confirmCancelDesc: "ایہ کੰਮ ਵਾਪਸ ਨਹੀਂ ਹੋ ਸਕਦਾ।",
    confirm:           "پکا کرو",
  },
  sd: {
    hotelName:      "کوئٽه هوٽل",
    welcome:        "ڀلي ڪري آيا",
    enterName:      "جاري رکڻ لاءِ پنهنجو نالو لکو",
    namePlaceholder:"توهان جو نالو يا ٽيبل نمبر",
    continueBtn:    "اڳتي وڌو",
    changeName:     "نالو تبديل ڪريو",
    menu:           "مينيو",
    myOrders:       "منهنجا آرڊر",
    addToCart:      "شامل ڪريو",
    placeOrder:     "آرڊر ڪريو",
    orderSummary:   "آرڊر جي تفصيل",
    total:          "ڪل",
    confirmOrder:   "آرڊر جي پڪ ڪريو",
    cancel:         "منسوخ",
    orderPlaced:    "آرڊر ملي ويو",
    status: {
      pending:   "انتظار",
      preparing: "پچي پيو",
      ready:     "تيار",
      served:    "ڏنو ويو",
      paid:      "ادا ٿيل",
      cancelled: "منسوخ",
    },
    payStatus: { unpaid: "باقي", partial: "اڌو اڌ", paid: "ادا ٿيل" },
    adminPanel:     "ايڈمن پينل",
    todayRevenue:   "اڄ جي ڪمائي",
    inKitchen:      "باورچي خاني ۾",
    ready2:         "تيار",
    unpaidOrders:   "باقي",
    orders:         "آرڊر",
    inventory:      "سامان",
    stock:          "برتن",
    searchOrders:   "نالي يا نمبر سان ڳوليو",
    all:            "سڀ",
    unpaidFilter:   "باقی",
    queueFilter:    "قطار",
    readyFilter:    "تيار",
    paidFilter:     "ادا",
    takePayment:    "پئسا وٺو",
    cancelOrder:    "منسوخ",
    newOrder:       "نيون آرڊر",
    cashSplit:      "روڪ",
    bankSplit:      "بينڪ",
    payment:        "ادائيگي",
    billFor:        "بل",
    grandTotal:     "ڪل رقم",
    alreadyPaid:    "اڳواٽ ادا ٿيل",
    remaining:      "باقي",
    howMuch:        "ڪيتري رقم؟ (روپيا)",
    fillFull:       "پوري رقم ڀريو",
    payMethod:      "ادائيگي جو طريقو",
    cash:           "روڪ",
    bank:           "بينڪ ٽرانسفر",
    save:           "محفوظ ڪريو",
    back:           "واپس",
    waiterView:     "ویٹر",
    readyToServe:   "ڏيڻ لاءِ تيار",
    recentlyServed: "تازو ڏنل",
    markServed:     "ڏنو ويو",
    noOrdersReady:  "ڪو به آرڊر تيار ناهي",
    kitchenDisplay: "باورچي خانو",
    startCooking:   "پچائڻ شروع ڪريو",
    readyToServeBtn:"تيار آهي",
    noOrders:       "ڪو به آرڊر ناهي",
    tapToAutofill:  "نالو پاڻمرادو ڀرڻ لاءِ هتي ڪلڪ ڪريو: ",
    confirmCancel:     "هي آرڊر منسوخ ڪريو؟",
    confirmCancelDesc: "هي عمل واپس نٿو ٿي سگهي.",
    confirm:           "پڪ ڪريو",
  },
} as const;

export type Translations = {
  [K in keyof typeof T["en"]]: typeof T["en"][K] extends string
    ? string
    : { [SubK in keyof typeof T["en"][K]]: string };
};

const LangContext = createContext<{ lang: Lang; t: Translations; setLang: (l: Lang) => void }>({
  lang: "en",
  t: T.en,
  setLang: () => {},
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("qh_lang") as Lang) ?? "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("qh_lang", l);
  };

  useEffect(() => {
    // Dynamic HTML text direction handling
    // English is LTR. All other regional languages listed (Urdu, Pushto, Balochi, Brahui, Persian, Punjabi, Sindhi) write RTL.
    const isRtl = lang !== "en";
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, t: T[lang], setLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export const LANG_OPTIONS: { value: Lang; label: string; flag: string }[] = [
  { value: "en",  label: "English",   flag: "🇬🇧" },
  { value: "ur",  label: "اردو",      flag: "🇵🇰" },
  { value: "ps",  label: "پښتو",      flag: "🏔️" },
  { value: "bal", label: "بلوچی",     flag: "🌴" },
  { value: "brh", label: "براہوئی",   flag: "🏺" },
  { value: "fa",  label: "فارسی",     flag: "🕌" },
  { value: "pa",  label: "پنجابی",    flag: "🌾" },
  { value: "sd",  label: "سنڌي",      flag: "🌊" },
];
